components:
  schemas:
    ProductCreate:
      type: object
      required:
        - name
        - reference
      properties:
        name:
          type: string
          example: T-Shirt
        reference:
          type: string
          example: "201"
    ProductUpdate:
      type: object
      properties:
        name:
          type: string
          description: Name of the product
        company_id:
          type: integer
          description: ID of the company
        description:
          type: string
          description: Description of the product
        notes:
          type: string
          description: Additional notes
        ean:
          type: string
          description: EAN for the product
        reference:
          type: string
          description: Reference code of the product
        status:
          type: string
          description: Status of the product
        ancestry:
          type: string
          description: Ancestry information for hierarchical data
        product_category_id:
          type: integer
          description: ID of the product category
        dimensions_unit:
          type: string
          description: Unit of measurement for product dimensions
        product_development_stage_id:
          type: integer
          description: ID of the product development stage
        development_stage_id:
          type: integer
          description: ID of the development stage
        component_level:
          type: string
          description: Level of the product component
        current_version:
          type: string
          description: Current version of the product
        version_name:
          type: string
          description: Name of the product version
        product_group_id:
          type: integer
          description: ID of the product group
        user_id:
          type: integer
          description: ID of the user
        supplier_id:
          type: integer
          description: ID of the supplier
        brand_id:
          type: integer
          description: ID of the brand
        wholesale_margin:
          type: number
          format: float
          description: Wholesale margin of the product
        retail_margin:
          type: number
          format: float
          description: Retail margin of the product
        wholesale_margin_type:
          type: string
          description: Type of wholesale margin
        retail_margin_type:
          type: string
          description: Type of retail margin
        direct_sale_margin:
          type: number
          format: float
          description: Direct sale margin of the product
        direct_sale_margin_type:
          type: string
          description: Type of direct sale margin
        development_stages_group_id:
          type: integer
          description: ID of the development stages group
        main_component_id:
          type: integer
          description: ID of the main component
        shopify_product_id:
          type: string
          description: Shopify product ID
    ProductResponse:
      type: object
      properties:
        id:
          type: string
          example: "fb13bf64-2897-45ff-a29d-c09fc384811d"
        name:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        companyId:
          type: integer
        description:
          type: string
        notes:
          type: string
        reference:
          type: string
        productCategory:
          type: string
        developmentStageId:
          type: integer
        componentLevel:
          type: string
        supplierId:
          type: integer
        brandId:
          type: integer
        developmentStagesGroupId:
          type: integer
        mainComponentId:
          type: integer
        developmentStage:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            color:
              type: string
        productPhotos:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              fileUrl:
                type: string
              position:
                type: integer
        variants:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              reference:
                type: string
              photoUrl:
                type: string
              variantPhotos:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    fileUrl:
                      type: string
              variantValues:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    content:
                      type: string
                    variantFieldId:
                      type: integer
              identifiers:
                type: array
                items:
                  type: object
                  properties:
                    productSize:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                    barcode:
                      type: string
                    sku:
                      type: string
                    identifierValues:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          content:
                            type: string
                          identifierField:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
        attachments:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              fileUrl:
                type: string
              name:
                type: string
              attachmentCategory:
                type: object
                properties:
                  en:
                    type: string
                  cn:
                    type: string
        productLabels:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              position:
                type: integer
              labelId:
                type: integer
              labelGroupId:
                type: integer
              labelGroupPosition:
                type: integer
        productValues:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              content:
                type: string
              productFieldId:
                type: integer
        sizeSets:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
        mainComponent:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            code:
              type: string
        components:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              code:
                type: string
