components:
  schemas:
    ReviewBase:
      type: object
      properties:
        name:
          type: string
          example: "Review name"
        orderId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        productId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        sizes:
          type: array
          items:
            type: string
            format: uuid
          example:
            - "123e4567-e89b-12d3-a456-426614174000"
            - "123e4567-e89b-12d3-a456-426614174000"
        status:
          type: integer
          description: "Review status, can be any of { approved: 0, approved_with_comments: 1, rejected: 2 }"
          enum:
            - 0
            - 1
            - 2
        generalComment:
          type: string
          example: "This is a general comment about the review."
        position:
          type: integer
          example: 1
        developmentStageId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        milestoneId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
      required:
        - name

    ReviewResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/ReviewBase'
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        userId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        createdAt:
          type: string
          format: date-time
          example: "2024-09-01T12:34:56Z"
        hasPendingRevisions:
          type: boolean
          example: true
        reviewPhotos:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                example: "123e4567-e89b-12d3-a456-426614174000"
              uuid:
                type: string
                format: uuid
                example: "123e4567-e89b-12d3-a456-426614174000"
              fileUrl:
                type: string
                format: uri
                example: "https://example.com/photos/photo.jpg"
              reviewed:
                type: boolean
                example: false
              position:
                type: integer
                example: 1
              commentedFileUrl:
                type: string
                format: uri
                example: "https://example.com/photos/commented_photo.jpg"
              initialFileUrl:
                type: string
                format: uri
                example: "https://example.com/photos/initial_photo.jpg"
              pinturaState:
                type: string
              shapes:
                type: string
        sampleReviewMeasures:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                example: "123e4567-e89b-12d3-a456-426614174000"
              measure:
                type: string
                example: "50 cm"
              productDimensionId:
                type: string
                format: uuid
                example: "123e4567-e89b-12d3-a456-426614174000"
              productSizeId:
                type: string
                format: uuid
                example: "123e4567-e89b-12d3-a456-426614174000"
        user:
          type: object
          properties:
            id:
              type: string
              format: uuid
              example: "123e4567-e89b-12d3-a456-426614174000"
            fullName:
              type: string
              example: "John Doe"
            firstName:
              type: string
              example: "John"
        developmentStage:
          type: object
          properties:
            id:
              type: string
              format: uuid
              example: "123e4567-e89b-12d3-a456-426614174000"
            name:
              type: string
              example: "Development Stage Name"
            color:
              type: string
              example: "gray"
