components:
  schemas:
    OrderBase:
      type: object
      properties:
        companyId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        status:
          type: integer
          description:
            "Order status, can be any of { not_finalized: 0, in_progress: 1, completed: 2, late: 3, exception: 4, draft: 5, pending_review: 6 }"
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
          example: 1
        supplierId:
          type: integer
          example: 120
        manufacturerLocationId:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        manufacturerContactId:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        shippingMethod:
          type: string
          example: "Shipping Method"
        shippingDate:
          type: string
          format: date-time
          example: "2021-01-01T00:00:00Z"
        paymentTerms:
          type: string
        incoterms:
          type: integer
          description:
            "Incoterms, can be any of { exw: 0, fca: 1, cpt: 2, cip: 3, dap: 4, dpu: 5, ddp: 6, fas: 7, fob: 8, cfr: 9, cif: 10 }"
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
          example: 1
        confirmed:
          type: boolean
          example: true
        currency:
          type: integer
          description:
            "Currency, can be any of { usd: 0, eur: 1, gbp: 2, cny: 3 }"
          enum:
            - 0
            - 1
            - 2
            - 3
          example: 1
        rechainSupport:
          type: boolean
        referenceName:
          type: string
        shippingAddressId:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        billingAddressId:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        paymentDeadline:
          type: string
          format: date
          example: "2021-01-01"
        invoiceDate:
          type: string
          format: date
          example: "2021-01-01"
        notes:
          type: string
        inventorySynced:
          type: boolean
        orderMode:
          type: integer
          description: "Order mode, can be any of { fpp: 0, cmt: 1 }"
          enum:
            - 0
            - 1
          example: 1
        exFactoryDate:
          type: string
          format: date
        currencies:
          type: array
          items:
            type: string
    OrderResponse:
      type: object
      properties:
        count:
          type: integer
        exceptionCount:
          type: integer
        lateCount:
          type: integer
        inProgressCount:
          type: integer
        completedCount:
          type: integer
        draftCount:
          type: integer
        pendingReviewCount:
          type: integer
        id:
          type: integer
        uuid:
          type: string
        reference:
          type: string
        unitsProduced:
          type: integer
        createdAt:
          type: string
          format: date-time
        country:
          type: string
        manufacturerLocation:
          $ref: '#/components/schemas/Location'
        manufacturerContact:
          $ref: '#/components/schemas/Contact'
        contact:
          type: string
        productCategory:
          type: string
        supplierCompany:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
        shippingDate:
          type: string
          format: date
        totalQuantity:
          type: integer
        productId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        productIds:
          type: array
          items:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
        otherPartyCompany:
          type: string
        orderProducts:
          type: array
          items:
            $ref: '#/components/schemas/OrderProduct'
        productSizes:
          type: array
          items:
            type: string
        company:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
        currentMilestoneGroupId:
          type: integer
        milestoneGroups:
          type: array
          items:
            $ref: '#/components/schemas/MilestoneGroup'

    OrderProduct:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        name:
          type: string
        variantId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        parentId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        parentName:
          type: string
        quantity:
          type: integer
        pricePerUnit:
          type: number
          format: float
        sizesQuantity:
          type: object
        productSizes:
          type: array
          items:
            type: string
        prices:
          type: object
    Location:
      type: object
      properties:
        id:
          type: integer
        country:
          type: string

    Contact:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    MilestoneGroup:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000-id"
        recordId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        position:
          type: integer
        objectType:
          type: string
          example: "milestoneGroup"
        name:
          type: string
        color:
          type: string
        start:
          type: string
          format: date
        end:
          type: string
          format: date
        milestones:
          type: array
          items:
            $ref: '#/components/schemas/Milestone'

    Milestone:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000-id"
        milestoneGroupId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        recordId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        orderId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        status:
          type: integer
          description: "Milestone status, can be any of { pending: 0, in_progress: 1, exception: 2, late: 3, completed: 4 }"
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
          example: 1
        humanizedStatus:
          description: "Milestone status, can be any of pending, in_progress, exception, late, completed }"
          type: string
        objectType:
          type: string
          example: "milestone"
        name:
          type: string
        start:
          type: string
          format: date
        end:
          type: string
          format: date
        position:
          type: integer
