components:
  schemas:
    BomTemplateBase:
      type: object
      properties:
        name:
          type: string
          example: "Template Name"
        companyId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
      required:
        - name
        - companyId
    BomTemplateResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/BomTemplateBase'
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        bomTemplateComponents:
          type: array
          items:
            type: string
