components:
  schemas:
    TrackerBase:
      type: object
      properties:
        name:
          type: string
          example: "Tracker Name"
        description:
          type: string
          example: "This tracker monitors the development progress."
        status:
          type: string
          example: "active"
        filters:
          type: object
          additionalProperties: true
          example: {
            brands: [],
            labels:
              [{id: "5d613b4c-7778-4feb-adf1-dd16e0c77ead",
                name: "Agent 1",
                label_group_id: "fe106f71-8746-4ab6-bf7e-dbaae98bba8f",
                label_group_name: "Agents"}],
            suppliers: [],
            product_categories:
              [{en: "Shorts",
                id: "2d55fe77-abfc-4a25-871c-7cdff943fd3c",
                company_id: "0f63f61c-93ce-4f7d-8324-94eeb5926a21"}]
          }
        userId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        companyId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        required:
          - name
          - companyId
    TrackerResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        createdAt:
          type: string
          format: date-time
          example: "2024-09-04T10:15:30Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-09-04T11:30:45Z"
        trackerPhotos:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                example: "123e4567-e89b-12d3-a456-426614174001"
              fileUrl:
                type: string
                format: url
                example: "https://example.com/photo.jpg"
        trackerProducts:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                example: "123e4567-e89b-12d3-a456-426614174002"
              productId:
                type: string
                format: uuid
                example: "123e4567-e89b-12d3-a456-426614174003"
              developmentTrackerId:
                type: string
                format: uuid
                example: "123e4567-e89b-12d3-a456-426614174000"
      allOf:
        - $ref: '#/components/schemas/TrackerBase'
