components:
  schemas:
    DevelopmentStage:
      type: object
      properties:
        name:
          type: string
          example: "Development Stage Name"
        position:
          type: integer
          example: 5
        company_id:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        isDefault:
          type: boolean
          example: true
        color:
          type: string
          example: "gray"
      required:
        - name
        - company_id
    DevelopmentStageResponse:
      type: object
      properties:
        id:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
      allOf:
        - $ref: '#/components/schemas/DevelopmentStage'
